"""Add theme to user

Revision ID: 63cbfd41fad7
Revises: d9d3584b6089
Create Date: 2026-08-01 21:27:26.332664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63cbfd41fad7'
down_revision = 'd9d3584b6089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('notification_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('failure_sound', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('failure_sound')
        batch_op.drop_column('notification_enabled')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
