"""Initial schema

Revision ID: d9d3584b6089
Revises: 
Create Date: 2026-07-26 00:18:33.476921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d3584b6089'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('requirement', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('expected_result', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('non_conformance_message', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('metric_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.drop_column('expected_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_specifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_text', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('unit',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('metric_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('non_conformance_message')
        batch_op.drop_column('expected_result')
        batch_op.drop_column('requirement')
        batch_op.drop_column('validation_type')

    # ### end Alembic commands ###
