"""Initial database schema

Revision ID: dd6d2eabfd05
Revises: 
Create Date: 2026-08-08 00:21:01.218542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6d2eabfd05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('company_code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('cable_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('pair_count', sa.String(length=10), nullable=False),
    sa.Column('conductor_size', sa.String(length=20), nullable=False),
    sa.Column('voltage_rating', sa.String(length=50), nullable=False),
    sa.Column('drain_configuration', sa.String(length=20), nullable=False),
    sa.Column('conductor_material', sa.String(length=50), nullable=False),
    sa.Column('insulation_material', sa.String(length=50), nullable=False),
    sa.Column('fire_resistant_material', sa.String(length=30), nullable=True),
    sa.Column('inner_sheath_material', sa.String(length=30), nullable=True),
    sa.Column('armour_type', sa.String(length=30), nullable=True),
    sa.Column('outer_sheath_material', sa.String(length=30), nullable=True),
    sa.Column('flame_retardant', sa.String(length=20), nullable=True),
    sa.Column('application', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('line_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('supervisor', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('failure_sound', sa.Boolean(), nullable=True),
    sa.Column('inspection_notification', sa.Boolean(), nullable=True),
    sa.Column('deviation_notification', sa.Boolean(), nullable=True),
    sa.Column('capa_notification', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_company_email'),
    sa.UniqueConstraint('company_id', 'username', name='uq_company_username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cable_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('drum_number', sa.String(length=50), nullable=False),
    sa.Column('drain_wire_type', sa.String(length=5), nullable=False),
    sa.Column('specialty', sa.String(length=5), nullable=False),
    sa.Column('water_barrier', sa.String(length=5), nullable=False),
    sa.Column('outer_sheath_colour', sa.String(length=10), nullable=False),
    sa.Column('cable_code', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('cable_type_id', sa.Integer(), nullable=False),
    sa.Column('production_line_id', sa.Integer(), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=False),
    sa.Column('cable_length', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cable_type_id'], ['cable_types.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['production_line_id'], ['production_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('cable_type_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('validation_type', sa.String(length=20), nullable=False),
    sa.Column('minimum_value', sa.Float(), nullable=True),
    sa.Column('maximum_value', sa.Float(), nullable=True),
    sa.Column('requirement', sa.String(length=150), nullable=True),
    sa.Column('expected_result', sa.String(length=200), nullable=True),
    sa.Column('non_conformance_message', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cable_type_id'], ['cable_types.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('inspection_number', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('inspector', sa.String(length=100), nullable=False),
    sa.Column('inspection_date', sa.Date(), nullable=False),
    sa.Column('overall_result', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['cable_batches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_number')
    )
    op.create_table('quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('measured_value', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['quality_specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deviations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deviation_number', sa.String(length=50), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('quality_metric_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reported_by', sa.String(length=100), nullable=False),
    sa.Column('reported_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['quality_metric_id'], ['quality_metrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deviation_number')
    )
    op.create_table('capa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('deviation_id', sa.Integer(), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=False),
    sa.Column('preventive_action', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('effectiveness', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['deviation_id'], ['deviations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('capa')
    op.drop_table('deviations')
    op.drop_table('quality_metrics')
    op.drop_table('inspections')
    op.drop_table('quality_specifications')
    op.drop_table('notifications')
    op.drop_table('cable_batches')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('production_lines')
    op.drop_table('customers')
    op.drop_table('cable_types')
    op.drop_table('companies')
    # ### end Alembic commands ###
